// Copyright (C) May 2022, Belmont Computing, Inc. -- All Rights Reserved
// Licensed under the BCI License. See LICENSE for details.

// ----Code generated by athos_rom_info.py script------//

#ifndef _F_ATHOS_ROM_INFO_H__
#define _F_ATHOS_ROM_INFO_H__

static const char chip_info[128] __attribute__((section(".chip_info"))) = 
  "---   Version:  athos-soc-v1.1-78-g315d354  Build Date: 2021-11-08, 14:54:32\r";
#endif  // _F_ATHOS_ROM_INFO_H__


